export default {
  products: [
    {
      _id: '1',
      name: 'Fresh Organic Tomatoes',
      image: '/images/pd1.jpg',
      category: 'Vegetables',
      description:'Buy fresh and organic Tomatoes. Our tomatoes are organic with no chemicals.',
      price: 20.00,
      rating: 4.5,
      review: 10,
    },
    {
     _id: '2',
      name: 'Tomatoes',
      image: '/images/pd1.jpg',
      category: 'Vegetables',
      description: 'Buy fresh and organic Tomatoes. Our tomatoes are organic with no chemicals.',
      price: 20.00,
      rating: 4.5,
      review: 10,
    },
    {
      _id: '3',
      name: 'Fresh  Tomatoes',
      image: '/images/pd1.jpg',
      category: 'Vegetables',
      description: 'Buy fresh and organic Tomatoes. Our tomatoes are organic with no chemicals.',
      price: 20.00,
      rating: 4.5,
      review: 10,
    },
    {
      _id: '4',
      name: 'Organic Tomatoes',
      image: '/images/pd1.jpg',
      category: 'Vegetables',
      description: 'Buy fresh and organic Tomatoes. Our tomatoes are organic with no chemicals.',
      price: 20.00,
      rating: 4.5,
      review: 10,
    },
    {
      _id: '5',
      name: 'Tomatoes',
      image: '/images/pd1.jpg',
      category: 'Vegetables',
      description: 'Buy fresh and organic Tomatoes. Our tomatoes are organic with no chemicals.',
      price:20.00,
      rating: 4.5,
      review: 10,
    },
    {
      _id: '6',
      name: 'Fresh Mangoes',
      image: '/images/pd1.jpg',
      category: 'Vegetables',
      description: 'Buy fresh and organic Tomatoes. Our tomatoes are organic with no chemicals.',
      price: 20.00,
      rating: 4.5,
      review: 10,
    },
  ],
};